{
    'name': 'Marble Serial Tracking',
    'version': '18.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Track Marble Pieces with Dimensions and Unique Serials',
    'author': 'ALPHAQUEB CONSULTING',
    'website': 'https://alphaqueb.com',
    'company': 'ALPHAQUEB CONSULTING S.A.S.',
    'maintainer': 'ANTONIO QUEB',
    'depends': ['purchase', 'stock',  'sale_management', 'sale_stock', 'marble_pedimento_tracking', 'marble_product_base'],
    'data': [
        'data/ir_sequence_data.xml',
        'views/purchase_order_views.xml',
        'views/stock_move_line_views.xml',
        'views/stock_quant_views.xml',
        'views/stock_picking_views.xml',
        'views/sale_order_views.xml',
        'views/product_template_views.xml',  
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
